### ISSUE TITLE
Change Shape of technology Artifact

### ISSUE THREAD

**Issue by DTHerrera** [plantuml-stdlib/Archimate-PlantUML#13]
How I can change the shape of technology artifacts?

For example, the artifacts shown in the following image

![TechnologyArtifacts](https://user-images.githubusercontent.com/36610780/80651637-df2a0d00-8a3b-11ea-903a-4ddebeb79a35.PNG)

thanks and regards

**Comment by DTHerrera** [comment]
Hello any comments about this request.

It's really very useful to me, and I'm pretty urgent.

I appreciate any comments you can give me.

Greetings

**Comment by joseluis** [comment]
Hello @DTHerrera , for what I've been able to find it's not possible for users to create new shapes, but only by modifying the code of  [PlantUML](https://github.com/plantuml/plantuml). Nothing to do about it in this repo which is just a collection of macro definitions.
If you search for "shapes" [in their forum](https://forum.plantuml.net/search?q=shapes) you can see people asking for custom shapes since 2015 so I wouldn't keep my hopes up.

**Comment by DTHerrera** [comment]
Hello thank you very much for your information, it really is bad news, I understand that there must be a core that should not be modified, but you must have an option to extend the functionality as libraries

**Comment by Potherca** [comment]
As this problem lies beyond the scope of this project, I am closing this issue.
